
NAVIDROME="${SYNOPKG_PKGDEST}/bin/navidrome"
CONF_FILE="${SYNOPKG_PKGVAR}/navidrome.toml"
ENV="HOME=${SYNOPKG_PKGVAR} ND_CONFIGFILE=${CONF_FILE} ND_PORT=4533"
SERVICE_COMMAND="env ${ENV} ${NAVIDROME}"
SVC_BACKGROUND=y
SVC_WRITE_PID=y
