SPK_NAME = wavemon
SPK_VERS = 0.9.4
SPK_REV = 1

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
COMMENT  = wavemon is a wireless device monitoring application that allows you to watch signal and noise levels, packet statistics, device configuration and network parameters of your wireless network hardware. It should work (though with varying features) with all devices supported by the Linux kernel.
STARTABLE = no

HOMEPAGE = https://github.com/uoaerg/wavemon
LICENSE  = GPL-3.0

SPK_COMMANDS = bin/wavemon

include ../../mk/spksrc.spk.mk
