SPK_NAME = synoedit
SPK_VERS = 0.0.8
SPK_REV = 1
SPK_ICON = src/synoedit.png

DEPENDS = cross/$(SPK_NAME)
UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = publicarray
DESCRIPTION =
DISPLAY_NAME = synoedit
HELPURL = https://github.com/publicarray/synoedit
LICENSE = "Synology package for editing files through a web interface using codemirror"
CHANGELOG = "First release"

STARTABLE=no
DSM_UI_DIR = ui
SERVICE_TYPE = legacy
SERVICE_URL = /webman/3rdparty/synoedit/index.cgi

include ../../mk/spksrc.spk.mk
